### ISSUE TITLE
When running pwmetrics on Travis CI it exits with code 0 and a ' Cannot read property 'ttfcp' of undefined.'

### ISSUE THREAD

**Issue by mAiNiNfEcTiOn** [paulirish/pwmetrics#138]
#### `pwmetrics-config.js`:

```js
module.exports = {
  url: 'https://www.google.pt',
  flags: {
    chromeFlags: [],
    expectations: false,
    perf: true,
    port: 9222,
    runs: 1,
    submit: false
    upload: false
    view: false
  },
}
```

#### `package.json`:

```json
{
  "name": "lighthouse-ci-poc",
  "version": "1.0.0",
  "description": "Attempt to make a Lighthouse CI configurable",
  "main": "index.js",
  "scripts": {
    "start": "pwmetrics --config=./pwmetrics-config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mAiNiNfEcTiOn/lighthouse-ci-poc.git"
  },
  "keywords": [
    "Lighthouse",
    "CI",
    "pwmetrics"
  ],
  "author": "Ricardo Machado <pt.n00b@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/mAiNiNfEcTiOn/lighthouse-ci-poc/issues"
  },
  "homepage": "https://github.com/mAiNiNfEcTiOn/lighthouse-ci-poc#readme",
  "dependencies": {
    "lighthouse": "^2.3.0",
    "pwmetrics": "^3.1.0"
  }
}
```

#### `.travis.yml`:

```yaml
sudo: required
language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker pull justinribeiro/chrome-headless
  - docker run -d --net host justinribeiro/chrome-headless
  - docker ps -a

install:
  - npm install

script:
  - node_modules/.bin/pwmetrics --config=./pwmetrics-config.js
```

### Steps to reproduce.

Well, this is a Travis CI yaml, if you use the same, you'll be able to reproduce.

The strange aspect is that with `lighthouse`, using @justinribeiro's chrome-headless docker image it works fine, it gathers the metrics and all.

With pwmetrics it fails (which should use lighthouse for the metrics), right?

### Stack trace
There's no stack trace, only an error saying:

`Unable to complete run 1 of 1 due to Cannot read property 'ttfcp' of undefined.`

### Screenshot

I could take screenshots, but this links point to the builds (one with lighthouse another with pwmetrics).

* Using Lighthouse: https://travis-ci.org/mAiNiNfEcTiOn/lighthouse-ci-poc/builds/258519392
* Using pwmetrics: https://travis-ci.org/mAiNiNfEcTiOn/lighthouse-ci-poc/builds/258518216

### Environment
1. `pwmetrics` version: ^3.1.0
2. Chrome version: latest stable on chrome-headless
3. OS version: Debian Trusty
